### ISSUE TITLE
PyMol visualizing not working

### ISSUE THREAD

**Issue by Suzehva** [dockstring/dockstring#167] opened 2023-12-06 02:56 UTC
I am trying to visualize my docking results using target.view(aux[ligand]) but I keep getting this error:

/Users/suze/anaconda3/envs/dockstring/bin/pymol: line 2: /Users/runner/miniforge3/conda-bld/pymol-open-source_1678980898696/_build_env/venv/bin/cross-python: No such file or directory
/Users/suze/anaconda3/envs/dockstring/bin/pymol: line 2: exec: /Users/runner/miniforge3/conda-bld/pymol-open-source_1678980898696/_build_env/venv/bin/cross-python: cannot execute: No such file or directory

I am running everything in conda and have installed pyMol through the command in the tutorial. Getting binding affinities does work, just the visualizing part is not working.

I would like to visualize stuff for a project that's due this Friday so I would appreciate any answer before that over a really good one after Friday. Thank you in advance!

**Comment by AustinT** [comment] 2023-12-06 10:21
Hello @Suzehva . Thanks for your interest in dockstring. First, looking at your error message it looks like an error with your pymol installation rather than an error with dockstring. Second, I re-ran the tutorial on my M1 Mac and it worked fine. Therefore I think this is not an issue with dockstring so I will close the issue.

If you think it is an issue with dockstring then feel free to re-open this issue, but please provide more information about the error and how to reproduce it (e.g. what commands did you run, what packages are in your environment, what operating system are you using).

**Closed by AustinT** 2023-12-06 10:21 UTC
