### ISSUE TITLE
pymol not visualize

### ISSUE THREAD

**Issue by PARODBE** [dockstring/dockstring#146] opened 2022-11-14 12:50 UTC
Hi,

when I try to visualize the docking I am obtaining the next error: 

![image](https://user-images.githubusercontent.com/62376157/201664560-7f959d25-c538-4cc7-8337-52ac6e7b9590.png)

Could you help me please?

Thanks!

**Comment by mgarort** [comment] 2022-11-14 16:17
Hi @PARODBE , the error you are getting seems a system-wide issue rather than something due to DOCKSTRING. It suggests that there is an installation error with PyMol. 

Have you followed the installation instructions in conda, and are you using the conda version of PyMol? If you are having problems, you should use the conda version of PyMol rather than the system-wide one.

After you install the DOCKSTRING environment, activate it with `conda activate dockstring` and then install PyMol with `conda install -c conda-forge pymol-open-source`.

Hope that helps.

**Comment by PARODBE** [comment] 2022-11-14 16:35
Hi,

Thank you for your so faster response! I obtain the same problem, maybe is for pymol version??? Could you fix this problem including pymol within the environment... My pymol version is 2.5.0:

![image](https://user-images.githubusercontent.com/62376157/201714873-645de58a-09ce-4521-9610-5aa2f5861a10.png)


Thank you!

**Comment by mgarort** [comment] 2022-11-14 21:59
Hi @PARODBE, I have just installed PyMol

`pymol-open-source         2.5.0            py37h1c7ad48_5    conda-forge` (same version)

 and I don't experience this problem. What operating system and version are you using? Does this issue occur only when used together with DOCKSTRING, or more generally whenever you try to use PyMol? 

It looks like it may be a system-wide problem that is unrelated to DOCKSTRING...

**Comment by PARODBE** [comment] 2022-11-15 09:17
I only obtain this problem when I try to visualize the pose. I am using dockstring with ubuntu 18.04.5

**Comment by PARODBE** [comment] 2022-11-16 08:53
Yes, following your steps I can open pymol but only in windows:

![image](https://user-images.githubusercontent.com/62376157/202128422-9b0dc00b-bb17-4962-98c9-9b2fc167f1c1.png)

if i follow the same steps in ubuntu i obtain the error: 

![image](https://user-images.githubusercontent.com/62376157/202133772-46229b97-e871-45b6-a33c-afb1ac81bbed.png)

**Comment by mgarort** [comment] 2022-11-16 16:58
I see. That is annoying... :/

Unfortunately I do not know how to fix this because it is a system error related to PyMol and the graphics in your Ubuntu system. It is not clear from the description whether your are using real Ubuntu, a virtual machine or the Windows Subsystem for Linux (WSL). Virtual machines or the WSL are more difficult to set up for graphics programs. I can use PyMol normally in my (real) Ubuntu, so I am unable to reproduce the error. I suggest asking a local systems administrator who can interact more directly with your computer.

I am closing this issue now since it does not depend on DOCKSTRING.

**Closed by mgarort** 2022-11-16 16:58 UTC
