### ISSUE TITLE
Docking takes a very long time to start

### ISSUE THREAD

**Issue by kheyer** [dockstring/dockstring#173] opened 2024-04-11 20:29 UTC
Having a weird issue. I think it's a vina issue but I'm interfacing through dockstring so this is the first level of triage.

I'm using the following code to dock SMILES inputs:

```python
def dock_smile(smile):
    target = load_target('EGFR')
    run_id = str(uuid.uuid1())

    working_dir=target.working_dir
    target_path=str(target.pdbqt_path)
    config_path=str(target.conf_path)

    vina_outfile = working_dir / f'vina_{run_id}.out'
    docked_ligand_pdb = working_dir / f'docked_ligand_{run_id}.pdb'

    ligand_mol_file = working_dir / f'ligand_{run_id}.mol'
    ligand_pdbqt = working_dir / f'ligand_{run_id}.pdbqt'
    canonical_smiles = canonicalize_smiles(smile)

    mol = smiles_to_mol(canonical_smiles, verbose=False)
    mol = sanitize_mol(mol, verbose=False)
    check_mol(mol)
    check_charges(mol)

    protonated_mol = protonate_mol(mol, pH=7.4)
    check_mol(protonated_mol)

    embedded_mol = embed_mol(protonated_mol, seed=42)
    refined_mol = refine_mol_with_ff(embedded_mol)
    assign_stereochemistry(refined_mol)

    write_mol_to_mol_file(refined_mol, ligand_mol_file)
    convert_mol_file_to_pdbqt(ligand_mol_file, ligand_pdbqt)

    vina_path = '/code/vina_1.2.5_linux_x86_64'

    cmd_list = [
        vina_path,
        '--receptor', target_path,
        '--config', config_path,
        '--ligand', ligand_pdbqt,
        '--out', vina_outfile,
        '--seed', str(DOCK_SEED),
        '--exhaustiveness', str(DOCK_EXHAUST),
        '--cpu', str(1),
        '--num_modes', str(DOCK_MODES)
    ]

    cmd_return = subprocess.run(cmd_list, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = cmd_return.stdout.decode('utf-8')

    convert_pdbqt_to_pdb(vina_outfile, docked_ligand_pdb)
    scores = parse_affinities_from_output(docked_ligand_pdb)

    return scores 
```

I'm running this code in a FastAPI server with multiple workers to run docking in parallel. I'm iteratively docking batches of ~1000 molecules at a time, with a maximum of 60 concurrent docking runs.

At first, everything works as expected and performance is great. I see 60 concurrent docking processes running at max capacity with little downtime between runs.

However, over time, the vina processes take longer and longer to start. `htop` shows vina processes listed in the `S` state for "interruptible sleep (waiting for an event to complete)". After docking ~10000 molecules, some vina processes take over and hour to initialize and I only see ~10 concurrent docking processes running.

I wanted to ask if this is a known issue with Vina, or if I need to explicitly close processes or delete files in my code.

**Comment by AustinT** [comment] 2024-04-11 22:31
Hi @kheyer , thanks for your interest in dockstring. I haven't encountered an issue like this, but maybe @mgarort can comment. The most molecules I have docked with a single program is ~10k. For larger runs everything was done as separate processes (e.g. reading in a file and docking molecules 500 to 600).

**Comment by mgarort** [comment] 2024-04-12 01:22
Hi @kheyer , I'm afraid I haven't encountered a similar issue before. I haven't used FastAPI before so your context may be different from my previous experience.

I would suspect the problem is related to the way you're parallelizing or aggregating the output from the different runs... Is there any variable or file that you are copying and appending to with each finishing process? Or could it be that you are getting close to running out of memory and the program is running on swap memory in the disk? 

It is hard to say what the culprit is but large-scale parallelization in a cluster-like environment can bring headaches in many ways 🙂

**Comment by AustinT** [comment] 2024-04-16 19:07
Sounds good, I'll close the issue then.

**Closed by AustinT** 2024-04-16 19:07 UTC
